apiVersion: v1
kind: PersistentVolume
metadata:
  name: he-voting-runtime-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: he-voting-host
  hostPath:
    path: /root/he_voting/runtime_k8s
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: he-voting-runtime
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: he-voting-host
  resources:
    requests:
      storage: 20Gi
